### ISSUE TITLE
HackSite - Footer com info

### ISSUE THREAD

**Issue by Lucasktrindade** [gdg-duque-de-caxias/gdg-duque-de-caxias.github.io#34]
Integrar com Twitter

**Comment by emanuelgsouza** [comment]
Pode me colocar para fazer esta parte. Só preciso saber como deve ser o form, tipo, quando o usuário clicar, a label irá subir, ou ele começa a digitar ao lado da label? Essas coisas

**Comment by Lucasktrindade** [comment]
Coloca no padrão do Material Design, com label subindo.

**Comment by emanuelgsouza** [comment]
Blz, pode deixar. É necessário um fw ou posso implementar somente esta funcionalidade?

**Comment by Lucasktrindade** [comment]
Não é necessário fw, pode implementar sem.

**Comment by emanuelgsouza** [comment]
Valeu!

**Comment by Lucasktrindade** [comment]
Merged
